### ISSUE TITLE
Finalise Flow Charts

### ISSUE THREAD

**Issue by CentIIO** [CentIIO/IS5006#3]
Draw flow chart using business language, don't use python terms

**Comment by amansinghania114** [comment]
Cool, i will look into it.

**Comment by CentIIO** [comment]
@amansinghania114 : Please finalize the remaining flow diagram and upload it for verification

**Comment by CentIIO** [comment]
Please validate the activity diagram uploaded and comment here for review if required @JackCChen2017 @amansinghania114

**Comment by amansinghania114** [comment]
Okay sure.

**Comment by amansinghania114** [comment]
Pretty solid, flowchart. Great work. Just that i feel there should be a call to plots as well.
